import { getNotificationPaths } from '../../../utils/shared/notificationSettings.js';

export const CONFIG_PATHS = [
    'input.mouseSpeed',
    'input.scrollSpeed',
    'input.touchDragHoldMs',
    'input.touchDragStillDistancePx',
    'preview.width',
    'preview.height',
    'preview.fps',
    'preview.hideDelayMs',
    'notifications.ttlMs',
    ...getNotificationPaths(),
    'samsungTv.enabled',
    'samsungTv.alwaysAutoResolve',
    'samsungTv.host',
    'samsungTv.mac',
    'samsungTv.port',
    'samsungTv.appName',
    'samsungTv.discoveryTimeoutMs',
    'samsungTv.timeoutMs',
    'samsungTv.pcInputKey',
    'samsungTv.pcInputSequence',
    'samsungTv.powerOffKey',
    'updateCheck.enabled',
    'qrOverlay.enabled',
    'qrOverlay.size',
    'qrOverlay.margin',
    'qrOverlay.topOffsetPx',
    'qrOverlay.autoHideOnHover',
    'qrOverlay.hoverEntryMarginPx',
    'qrOverlay.hoverExitMarginPx',
    'qrOverlay.hoverShowDelayMs',
    'logging.level',
    'logging.format',
];
