# frozen_string_literal: true

laboratory_directory = __dir__
repository_directory = File.expand_path("../..", laboratory_directory)

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "linux-install" do |guest|
    guest.vm.box = "cloud-image/ubuntu-24.04"
    guest.vm.box_version = "20260926.0.0"
    guest.vm.hostname = "remote-mouse-install"
    guest.vm.synced_folder repository_directory, "/workspace/remote-mouse",
      type: "rsync",
      rsync__exclude: ["/.git/", "/node_modules/", "/build/", "/coverage/", "/.data/"]
    guest.vm.provider :libvirt do |provider|
      provider.driver = "kvm"
      provider.cpus = 2
      provider.memory = 4096
      provider.storage_pool_name = "default"
    end

    guest.vm.provision "shell", name: "prepare-linux",
      path: File.join(laboratory_directory, "provision/prepare-linux-install.sh")
    guest.vm.provision "shell", name: "install-remote-mouse", privileged: false,
      path: File.join(laboratory_directory, "provision/install-remote-mouse.sh")
  end
end
