export const BROWSER_CATALOG = [
  {
    id: 'brave',
    name: 'Brave',
    shortLabel: 'Brave',
    linuxCommands: ['brave-browser', 'brave'],
    linuxProcessNames: ['brave-browser', 'brave'],
    linuxWindowClasses: ['brave'],
    linuxWindowNames: ['Brave'],
    linuxFlatpakAppId: 'com.brave.Browser',
    darwinApps: ['Brave Browser'],
    winCommands: ['brave'],
  },
  {
    id: 'chrome',
    name: 'Google Chrome',
    shortLabel: 'Chrome',
    linuxCommands: ['google-chrome', 'google-chrome-stable'],
    linuxProcessNames: ['google-chrome', 'chrome'],
    linuxWindowClasses: ['google-chrome', 'chrome'],
    linuxWindowNames: ['Google Chrome', 'Chrome'],
    darwinApps: ['Google Chrome'],
    winCommands: ['chrome'],
  },
  {
    id: 'chromium',
    name: 'Chromium',
    shortLabel: 'Chromium',
    linuxCommands: ['chromium-browser', 'chromium'],
    linuxProcessNames: ['chromium-browser', 'chromium'],
    linuxWindowClasses: ['chromium-browser', 'chromium'],
    linuxWindowNames: ['Chromium'],
    darwinApps: ['Chromium'],
    winCommands: ['chromium'],
  },
  {
    id: 'edge',
    name: 'Microsoft Edge',
    shortLabel: 'Edge',
    linuxCommands: ['microsoft-edge', 'microsoft-edge-stable'],
    linuxProcessNames: ['microsoft-edge', 'msedge'],
    linuxWindowClasses: ['microsoft-edge', 'msedge'],
    linuxWindowNames: ['Microsoft Edge', 'Edge'],
    darwinApps: ['Microsoft Edge'],
    winCommands: ['msedge', 'microsoft-edge'],
  },
  {
    id: 'firefox',
    name: 'Firefox',
    shortLabel: 'Firefox',
    linuxCommands: ['firefox'],
    linuxProcessNames: ['firefox'],
    linuxWindowClasses: ['firefox'],
    linuxWindowNames: ['Firefox'],
    darwinApps: ['Firefox'],
    winCommands: ['firefox'],
  },
  {
    id: 'safari',
    name: 'Safari',
    shortLabel: 'Safari',
    linuxCommands: [],
    darwinApps: ['Safari'],
    winCommands: [],
  },
];

export function getBrowserCatalogEntry(browserId) {
  return BROWSER_CATALOG.find((browser) => browser.id === browserId) || null;
}
